---
title: "Need the Ingredients"
type: "challenge"
description: "Use Telnet to understand POST requests"
visibility: "assign"
tags: "evening-exercise, http"
ignore:
- "evening-need-the-ingredients.md"
